command:
  - uv
  - run
  - start.py

env:
  - name: AGENT_PORT
    value: 8080
  - name: AGENT_CONNECT_TIMEOUT
    value: 30
  - name: AGENT_READ_TIMEOUT
    value: 600
  - name: AGENT_KEEPALIVE_SECS
    value: 600
  - name: MLFLOW_EXPERIMENT_ID
    value: 3622262438742193